
protected-zone:
  region-id: "clickerzone"

global-flags:
  #setting to decide whether Items are dropped (false) or deposited directly to the players inventory
  deposit-to-inventory: false
  #setting the bonus to the loot chance from fortune enchantments (in percent), this modifier is multiplicative.
  fortune-modifier-per-level: 10

#Define groups of tools to make drops individualized to certain tools
#Important: If tools are in multiple groups, they will drop loot from all the lists they are in.
tool-Groups:
  default:
    alwaysPossible: true
  shovels:
    tools:
      - "DIAMOND_SHOVEL"
      - "WOODEN_SHOVEL"

#The chance has to be given as a number between 0 and 1.
block-rewards:
  default:
    DIRT:
      xp: 0
      rewards:
        - item: "CLAY_BALL"
          amount: 5
          chance: 100
        - item: "DIAMOND"
          amount: 1
          chance: 50
  shovels:
    DIRT:
      xp: 100
      rewards:
        - item: "CLAY_BALL"
          amount: 5
          chance: 100
        - item: "DIAMOND"
          amount: 1
          chance: 50