protected-zone:
  #provide the name of the worldguard zone in which the plugin should work.
  region-id: "clickerzone"

global-flags:
  #setting to decide whether Items are dropped (false) or deposited directly to the players inventory
  deposit-to-inventory: false
  #setting the bonus to the loot chance from fortune enchantments (in percent), this modifier is multiplicative.
  fortune-modifier-per-level: 10

#Define groups of tools to make drops individualized to certain tools
#Important: If tools are in multiple groups, they will drop loot from all the lists they are in.
tool-Groups:
  default:
    alwaysPossible: true
  shovels:
    tools:
      - "DIAMOND_SHOVEL"
      - "WOODEN_SHOVEL"


#The chance has to be given as double between 0 and 100.
block-rewards:
  default:
    DIRT:
      xp: 0
      rewards:
        - item: "CLAY_BALL"
          amount: 5
          chance: 0
        - item: "DIAMOND"
          amount: 1
          chance: 50
  shovels:
    DIRT:
      xp: 100
      rewards:
        #You can create custom items via the bc saveitem <name of the Item> command while holding the item in your main hand
        #specification of the amount is facultative. If not provided, it is assumed to be the same amount as the item used in the creation of the key
        #be warned, using amount != 1 for an unstackable Item does still give a stack of this unstackable Item.

        # You can award a custom reward like this (create the item, replace oldShovel by your items name and remove the  #in the following lines)

        #- item: "oldShovel"
          #is-custom: true
          #amount: 5
          #chance: 100
        - item: "CLAY_BALL"
          amount: 5
          chance: 0
        - item: "DIAMOND"
          amount: 1
          chance: 50